#!/usr/bin/env perl

require 5.016;

use strict;
use warnings;
use FindBin;
BEGIN { 
    unshift @INC, "$FindBin::Bin/../lib";
    unshift @INC, "$FindBin::Bin/../ext_lib/mach";
    unshift @INC, "$FindBin::Bin/../ext_lib"; }
# Start command line interface for application
require Mojolicious::Commands;

Mojolicious::Commands->start_app('Textmining');
