#!/usr/bin/env perl

require 5.006;

use strict;
use warnings;
use FindBin;
BEGIN {
    unshift @INC, "$FindBin::Bin/../lib",
    push @INC, "$FindBin::Bin/../ext_lib",
}
# Start command line interface for application
require Mojolicious::Commands;
require Data::Printer;
require Exporter;
require File::Basename;
require File::Copy::Recursive;
require File::Glob;
require File::Path;
require File::Spec::Functions;
#require Math::Combinatoric;
require Mojolicious;
require Storable;
require Text::NSP;
require XML::LibXML;
require XML::LibXSLT;


Mojolicious::Commands->start_app('Textmining');
