#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { 
    unshift @INC, "$FindBin::Bin/../lib",
    push @INC, "$FindBin::Bin/../ext_lib",
    push @INC, "$FindBin::Bin/../ext_lib/mach" }

# Start command line interface for application

require Mojolicious::Commands;

Mojolicious::Commands->start_app('Textmining');
