#!/usr/bin/env perl

require 5.006;

use strict;
use warnings;
use FindBin;
BEGIN {
    unshift @INC, "$FindBin::Bin/../lib",
    push @INC, "$FindBin::Bin/../ext_lib",
}
# Start command line interface for application
require Mojolicious::Commands;

Mojolicious::Commands->start_app('Textmining');
